path: D:\programiranje_D\gesture_recognition\Prepoznavanje-gest-v-avtonomni-voznji\dataset
train: images\train
val: images\validation


names:
  0: fist
  1: hand
  2: peace
  3: thumbs up
  4: none

